[package]
name = "rust-ps"
version = "0.1.0"
edition = "2021"

[dev-dependencies]
criterion = "0.5"

[profile.dev]
opt-level = 1

[profile.release]
opt-level = 3
lto = true

[[bench]]
name = "algorithm_bench"
harness = false
path = "benches/algorithm_bench.rs"
